apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi  # Taille du disque pour MySQL
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # Le disque est monté en lecture-écriture sur un seul pod
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: mysql-disk  # Nom du disque GCE pour MySQL
    fsType: ext4
